# Generated by Django 4.0.5 on 2022-07-14 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('categorie', models.CharField(choices=[('CS', 'Chambre Simple'), ('CD', 'Chambre Double'), ('CDL', 'Chambre de Luxe'), ('App', 'Appartement')], max_length=3)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/images')),
                ('disponibilite', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualite', models.CharField(choices=[('Mr', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle'), ('Autres', 'Autres')], max_length=6)),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=25)),
                ('adresse', models.CharField(max_length=25)),
                ('telephone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEntre', models.DateTimeField()),
                ('dateSorti', models.DateTimeField()),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionHost.chambre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionHost.client')),
            ],
        ),
    ]
