# Generated by Django 4.0.5 on 2022-07-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionHost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='categorie',
            field=models.CharField(choices=[('Chambre simple', 'Chambre Simple'), ('Chambre double', 'Chambre Double'), ('Chambre de luxe', 'Chambre de Luxe'), ('Appartement', 'Appartement')], max_length=15),
        ),
    ]
