# Generated by Django 4.0.5 on 2022-07-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionHost', '0002_alter_chambre_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='chambre',
            name='image',
            field=models.ImageField(upload_to='media/imageUser'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
