# Generated by Django 4.0.5 on 2022-08-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionHost', '0004_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='client',
        ),
    ]
